export const BOX_SIZE = 100;
export const STEP_SIZE = 10;
export const KEY_UP = 38;
export const KEY_DOWN = 40;
export const KEY_LEFT = 37;
export const KEY_RIGHT = 39;
export const INIT_POS = 10;
export const BOARD_WIDTH = window.innerWidth;
export const BOARD_HEIGHT = window.innerHeight / 2;